### ISSUE TITLE
jQuery Terminal attribution

### ISSUE THREAD

**Issue by jcubic** [maacpiash/maacpiash.github.io#3]
got link in referer from your site https://www.maacpiash.com/ how do you use jQuery Terminal? If you removed, it there is still info in the footer. This probably will confuse the user, since you don't use the library (you only linked it in head).

I'm not complaining but maybe this is just your mistake, you wanted to use it but then you created your own implementation and forget to remove the links and attribution.

**Comment by maacpiash** [comment]
Thank you for pointing out my mistake. I started the project with a view to using the library but did not do it.

Right now the 'terminal' that the website shows does not use the jQuery Terminal library. But I do want to incorporate some features that the library provides (e.g. auto-completion on tab-key-press), for which I would require the library.

I am removing the attribute for now. I will attach it later when I start using the library.

I thank you for your reporting and also commend you for the amazing library you wrote.
